### ISSUE TITLE
Question: why not mendoza?

### ISSUE THREAD

**Issue by pepe** [pyrmont/ecstatic#1]
Not to be rude, just if something is missing for you?

**Comment by pyrmont** [comment]
@pepe No, it's not rude. In fact, it's a good question. I did have a look at Mendoza but there were three reasons I decided to roll my own:

1. I wanted a project that would give me an excuse to play around with [Conjure](https://github.com/Olical/conjure).
2. I wanted to write my content files in CommonMark and with YAML-style frontmatter.
3. I just wanted to write some Janet :D

I am planning on using [Temple](https://git.sr.ht/~bakpakin/temple) for templates. I don't suppose you have any experience using them, do you? I'm curious whether you can have templates that you use within other templates. It sounds like maybe you can (the README says that 'Templates can be used recursively') but I'm not sure how you'd do it.

**Comment by pepe** [comment]
All reasons are perfectly valid! Thank you.

I used `temple` only for some basic Janet code (sic) generation in `chidi` https://github.com/good-place/chidi/tree/master/chidi/generate no nesting what so ever. But the thing is that it is quite clear code, you can examine yourself. Also, I have the experience with @bakpakin, that what is in README is in code.

PS: I would love to have Conjure for kakoune editor :-).

**Comment by pepe** [comment]
Well, if nothing more I gave Mendoza a bigger shot finally, and I like it.

I am looking forward to checking Statically!
